# Generated by Django 4.2.7 on 2023-11-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Complete status'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Public hosting'),
        ),
    ]
