# Generated by Django 4.2.7 on 2023-11-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quiz_private'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
    ]
