# Generated by Django 4.2.7 on 2023-12-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_audio_question_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Answer 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Answer 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Answer 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Answer 4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Question number'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Question text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Question type'),
        ),
    ]
