# Generated by Django 4.2.7 on 2023-12-03 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_quiz_category1_alter_quiz_category2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
