# Generated by Django 4.2.7 on 2023-12-03 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quiz_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizinstance',
            name='hosted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
