# Generated by Django 4.2.7 on 2023-12-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quizinstance_hosted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizinstance',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived status'),
        ),
    ]
