# Generated by Django 4.2.7 on 2023-12-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_quizinstance_completed_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizinstance',
            name='instance_type',
            field=models.IntegerField(default='0', verbose_name='Instance Type'),
        ),
    ]
