# Generated by Django 4.2.7 on 2023-12-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_participant_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='edit_only',
            field=models.BooleanField(default=False, verbose_name='Editing only'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden'),
        ),
    ]
