# Generated by Django 4.2.7 on 2023-12-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_remove_quizinstance_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
    ]
