# Generated by Django 4.2.7 on 2023-12-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_alter_quizinstance_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizinstance',
            name='player',
        ),
    ]
