# Generated by Django 4.2.7 on 2023-12-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_remove_quizinstance_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizinstance',
            name='instance_type',
        ),
        migrations.AddField(
            model_name='quizinstance',
            name='play_type',
            field=models.IntegerField(default='0', verbose_name='Play Type'),
        ),
    ]
