# Generated by Django 4.2.7 on 2023-12-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_quizinstance_multichoice_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizinstance',
            name='multichoice_only',
            field=models.BooleanField(default=False, verbose_name='Multichoice exclusive'),
        ),
    ]
