# Generated by Django 4.2.7 on 2023-12-11 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_user_public_host_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizinstance')),
            ],
            options={
                'verbose_name_plural': 'QuizInstance',
            },
        ),
    ]
