# Generated by Django 4.2.7 on 2023-12-19 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_alter_showcasequiz_options_quizinstance_local_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Team Name')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.participant')),
            ],
            options={
                'verbose_name_plural': 'QuizTeam',
            },
        ),
        migrations.CreateModel(
            name='QuizMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Member Name')),
                ('quiz_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizteam')),
            ],
            options={
                'verbose_name_plural': 'QuizMember',
            },
        ),
    ]
