# Generated by Django 4.2.7 on 2023-12-19 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_quizteam_quizmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmember',
            name='member_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.teammembers'),
        ),
        migrations.AlterField(
            model_name='quizmember',
            name='member_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Member Name (string)'),
        ),
        migrations.AlterField(
            model_name='quizteam',
            name='team_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Team Name'),
        ),
    ]
